openapi: 3.0.1
info:
  title: 'DevBook.Web.ApiService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /projects:
    get:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectCommand'
        required: true
      responses:
        '201':
          description: Created
  '/projects/{id}':
    get:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      operationId: GetProjectById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Not Found
    put:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    patch:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchProjectCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    delete:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
  /tasks:
    get:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkTask'
    post:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkTaskCommand'
        required: true
      responses:
        '201':
          description: Created
  '/tasks/{id}':
    get:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      operationId: GetWorkTaskById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkTask'
        '404':
          description: Not Found
    put:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkTaskCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    patch:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchWorkTaskCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    delete:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
components:
  schemas:
    CreateProjectCommand:
      required:
        - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    CreateWorkTaskCommand:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
          nullable: true
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    PatchProjectCommandDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    PatchWorkTaskCommandDto:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
          nullable: true
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    UpdateProjectCommandDto:
      required:
        - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    UpdateWorkTaskCommandDto:
      required:
        - start
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    WorkTask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false