openapi: 3.0.1
info:
  title: 'DevBook.Web.ApiService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /identity/logout:
    post:
      tags:
        - Identity
      operationId: Logout
      responses:
        '200':
          description: Success
  /identity/register:
    post:
      tags:
        - Identity
      operationId: Register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
  /identity/login:
    post:
      tags:
        - Identity
      operationId: Login
      parameters:
        - name: useCookies
          in: query
          style: form
          schema:
            type: boolean
        - name: useSessionCookies
          in: query
          style: form
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
  /identity/refresh:
    post:
      tags:
        - Identity
      operationId: Refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
  /identity/confirmEmail:
    get:
      tags:
        - Identity
      operationId: MapIdentityApi-/identity/confirmEmail
      parameters:
        - name: userId
          in: query
          style: form
          schema:
            type: string
        - name: code
          in: query
          style: form
          schema:
            type: string
        - name: changedEmail
          in: query
          style: form
          schema:
            type: string
      responses:
        '200':
          description: Success
  /identity/resendConfirmationEmail:
    post:
      tags:
        - Identity
      operationId: ResendConfirmationEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationEmailRequest'
      responses:
        '200':
          description: Success
  /identity/forgotPassword:
    post:
      tags:
        - Identity
      operationId: ForgotPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
  /identity/resetPassword:
    post:
      tags:
        - Identity
      operationId: ResetPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
  /identity/manage/2fa:
    post:
      tags:
        - Identity
      operationId: Manage2fa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFactorRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        '404':
          description: Not Found
  /identity/manage/info:
    get:
      tags:
        - Identity
      operationId: ManageInfo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        '404':
          description: Not Found
    post:
      tags:
        - Identity
      operationId: ManageInfo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        '404':
          description: Not Found
  /projects:
    get:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectCommand'
        required: true
      responses:
        '201':
          description: Created
  '/projects/{id}':
    get:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      operationId: GetProjectById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Not Found
    put:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    patch:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchProjectCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    delete:
      tags:
        - TimeTrackingModule_ProjectEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
  /tasks:
    get:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkTask'
    post:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkTaskCommand'
        required: true
      responses:
        '201':
          description: Created
  '/tasks/{id}':
    get:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      operationId: GetWorkTaskById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkTask'
        '404':
          description: Not Found
    put:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkTaskCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    patch:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchWorkTaskCommandDto'
        required: true
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    delete:
      tags:
        - TimeTrackingModule_WorkTaskEndpoints
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
components:
  schemas:
    AccessTokenResponse:
      type: object
      properties:
        tokenType:
          type: string
          nullable: true
          readOnly: true
        accessToken:
          type: string
          nullable: true
        expiresIn:
          type: integer
          format: int64
        refreshToken:
          type: string
          nullable: true
      additionalProperties: false
    CreateProjectCommand:
      required:
        - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    CreateWorkTaskCommand:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
          nullable: true
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    ForgotPasswordRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
      additionalProperties: false
    HttpValidationProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          nullable: true
      additionalProperties: { }
    InfoRequest:
      type: object
      properties:
        newEmail:
          type: string
          nullable: true
        newPassword:
          type: string
          nullable: true
        oldPassword:
          type: string
          nullable: true
      additionalProperties: false
    InfoResponse:
      type: object
      properties:
        email:
          type: string
          nullable: true
        isEmailConfirmed:
          type: boolean
      additionalProperties: false
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        twoFactorCode:
          type: string
          nullable: true
        twoFactorRecoveryCode:
          type: string
          nullable: true
      additionalProperties: false
    PatchProjectCommandDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    PatchWorkTaskCommandDto:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
          nullable: true
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
          nullable: true
      additionalProperties: false
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    ResendConfirmationEmailRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
      additionalProperties: false
    ResetPasswordRequest:
      type: object
      properties:
        email:
          type: string
          nullable: true
        resetCode:
          type: string
          nullable: true
        newPassword:
          type: string
          nullable: true
      additionalProperties: false
    TwoFactorRequest:
      type: object
      properties:
        enable:
          type: boolean
          nullable: true
        twoFactorCode:
          type: string
          nullable: true
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
      additionalProperties: false
    TwoFactorResponse:
      type: object
      properties:
        sharedKey:
          type: string
          nullable: true
        recoveryCodesLeft:
          type: integer
          format: int32
        recoveryCodes:
          type: array
          items:
            type: string
          nullable: true
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
      additionalProperties: false
    UpdateProjectCommandDto:
      required:
        - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        details:
          type: string
          nullable: true
        hourlyRate:
          type: integer
          format: int32
          nullable: true
        currency:
          type: string
          nullable: true
        hexColor:
          type: string
          nullable: true
      additionalProperties: false
    UpdateWorkTaskCommandDto:
      required:
        - start
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
    WorkTask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        projectId:
          type: string
          format: uuid
          nullable: true
        description:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        start:
          type: string
          format: time
        end:
          type: string
          format: time
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: Please enter token.
      scheme: bearer
security:
  - Bearer: [ ]